# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Editor.views import Editor


class UiMainWindow(object):
    def __init__(self, main_window):
        # ------------ #
        # Init objects #
        # ------------ #
        self.central_widget = QtWidgets.QWidget(main_window)
        self.tabWidget = QtWidgets.QTabWidget(self.central_widget)
        self.tab = QtWidgets.QWidget()
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.tab_2 = QtWidgets.QWidget()
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.actionOpen = QtWidgets.QAction(main_window)
        self.actionAbout = QtWidgets.QAction(main_window)
        self.actionHelp = QtWidgets.QAction(main_window)
        self.actionExit = QtWidgets.QAction(main_window)
        self.actionNew = QtWidgets.QAction(main_window)
        self.actionOpen_recent = QtWidgets.QAction(main_window)
        self.actionSave_as = QtWidgets.QAction(main_window)
        self.actionSave = QtWidgets.QAction(main_window)
        # --------------- #
        # Init connectors #
        # --------------- #
        self.editor = Editor(self)

    def setup_ui(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(800, 600)
        self.central_widget.setObjectName("central_widget")
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab.setObjectName("tab")
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 801, 531))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        main_window.setCentralWidget(self.central_widget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile.setObjectName("menuFile")
        self.menuHelp.setObjectName("menuHelp")
        main_window.setMenuBar(self.menubar)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionOpen_recent.setObjectName("actionOpen_recent")
        self.actionNew.setObjectName("actionNew")
        self.actionExit.setObjectName("actionExit")
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionOpen_recent)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.re_translate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def re_translate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionOpen_recent.setText(_translate("MainWindow", "Open recent"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
